
# ---------------------------------------------------------
# Runnable Parallel
# ---------------------------------------------------------
# RunnableParallel = run multiple chains/branches
# at the same time and return all results together.
#
# Example:
#
# Input
#   ├──→ Short explanation
#   └──→ Detailed explanation
#
# Both branches work independently.


# Load environment variables from .env
from dotenv import load_dotenv
load_dotenv()


# Import Mistral AI model
from langchain_mistralai import ChatMistralAI

# Used to create prompts
from langchain_core.prompts import ChatPromptTemplate

# Converts AI response into a normal Python string
from langchain_core.output_parsers import StrOutputParser

# RunnableParallel = multiple branches
# RunnableLambda = our custom Python function as a Runnable
from langchain_core.runnables import RunnableParallel, RunnableLambda


# ---------------------------------------------------------
# Components
# ---------------------------------------------------------

# Create the Mistral model
model = ChatMistralAI(model="mistral-small-2506")

# Create output parser
parser = StrOutputParser()


# ---------------------------------------------------------
# Prompt 1: Short explanation
# ---------------------------------------------------------

short_prompt = ChatPromptTemplate.from_template(
    "Explain {topic} in 1-2 lines"
)

# {topic} will be replaced by the topic we give.


# ---------------------------------------------------------
# Prompt 2: Detailed explanation
# ---------------------------------------------------------

detailed_prompt = ChatPromptTemplate.from_template(
    "Explain {topic} in detail"
)

# This prompt will ask the AI for a detailed explanation.

# ---------------------------------------------------------
# Runnable Parallel
# ---------------------------------------------------------

chain = RunnableParallel({

    # =====================================================
    # BRANCH 1 -> "short"
    # =====================================================

    "short":

        # x is the complete input given to chain.invoke()
        #
        # Example x:
        # {
        #     "short": {"topic": "Machine Learning"},
        #     "detailed": {"topic": "Deep Learning"}
        # }
        #
        # x['short'] gives:
        # {"topic": "Machine Learning"}
        #
        # So this Lambda selects ONLY the short input.
        RunnableLambda(lambda x: x["short"])

        # Now the selected input goes to short_prompt
        # and fills {topic}.
        |
        short_prompt

        # Send the prompt to Mistral AI
        |
        model

        # Convert AIMessage into normal string
        |
        parser,


    # =====================================================
    # BRANCH 2 -> "detailed"
    # =====================================================

    "detailed":

        # x['detailed'] gives:
        # {"topic": "Deep Learning"}
        #
        # So this Lambda selects ONLY the detailed input.
        RunnableLambda(lambda x: x["detailed"])

        # Now the selected input goes to detailed_prompt
        |
        detailed_prompt

        # Send prompt to Mistral AI
        |
        model

        # Convert result into a string
        |
        parser
})


# ---------------------------------------------------------
# Run the parallel chain
# ---------------------------------------------------------

result = chain.invoke({

    # Input for the "short" branch
    "short": {
        "topic": "Machine Learning"
    },

    # Input for the "detailed" branch
    "detailed": {
        "topic": "Deep Learning"
    }
})


# ---------------------------------------------------------
# Print results
# ---------------------------------------------------------

# Print output generated by short branch
print(result["short"])

# Print output generated by detailed branch
print(result["detailed"])

