
# Load variables from the .env file
# Example: MISTRAL_API_KEY=xxxxx
from dotenv import load_dotenv
load_dotenv()


# Import Mistral chat model
from langchain_mistralai import ChatMistralAI

# Used to create prompts
from langchain_core.prompts import ChatPromptTemplate

# Converts AIMessage output into a normal string
from langchain_core.output_parsers import StrOutputParser

# RunnableParallel -> runs multiple things in parallel
# RunnablePassthrough -> passes the input without changing it
from langchain_core.runnables import RunnableParallel, RunnablePassthrough


# Create the Mistral LLM
model = ChatMistralAI(model="mistral-small-2506")

# Create output parser
# It converts the model response into a simple string
parser = StrOutputParser()


# ---------------------------------------------------
# PROMPT 1: Generate code
# ---------------------------------------------------

code_prompt = ChatPromptTemplate.from_messages([
    # System message tells the AI its role
    ("system", "You are a code generator"),

    # {topic} will be replaced by our actual input
    ("human", "{topic}")
])


# ---------------------------------------------------
# PROMPT 2: Explain generated code
# ---------------------------------------------------

explain_prompt = ChatPromptTemplate.from_messages([
    # Tell the AI to explain code in simple language
    ("system", "You are a helpful assistant who explains code in simple terms"),

    # {code} will contain the code generated by the first chain
    ("human", "Explain the following code in simple words:\n{code}")
])


# ---------------------------------------------------
# SEQUENCE
# ---------------------------------------------------

# The | operator means:
#
# code_prompt → model → parser
#
# Step 1: Create the prompt
# Step 2: Send prompt to Mistral
# Step 3: Convert AI response into a string
seq = code_prompt | model | parser


# ---------------------------------------------------
# PARALLEL
# ---------------------------------------------------

seq2 = RunnableParallel(

    # "code":
    # RunnablePassthrough keeps the original input unchanged
    #
    # "explanation":
    # Takes the code and sends it to:
    # explain_prompt → model → parser
    {
        "code": RunnablePassthrough(),

        "explanation": explain_prompt | model | parser
    }
)


# ---------------------------------------------------
# COMPLETE CHAIN
# ---------------------------------------------------

# First run seq
#
# Input:
# {
#     "topic": "please write a code of palindrome in python"
# }
#
# seq generates the Python code.
#
# Then seq2 receives that generated code.
chain = seq | seq2


# ---------------------------------------------------
# RUN THE CHAIN
# ---------------------------------------------------

result = chain.invoke({
    "topic": "please write a code of palindrome in python "
})


# Print the generated code
print(result["code"])

# Print the explanation of that code
print(result["explanation"])

"""

User Input
   ↓
code_prompt
   ↓
Mistral AI
   ↓
parser
   ↓
Generated Python Code
   ↓
RunnableParallel
      ↙              ↘
   code          explanation
    ↓                 ↓
Passthrough     explain_prompt
                      ↓
                  Mistral AI
                      ↓
                    parser
                    
                    
"""